# Generated by Django 4.2.7 on 2023-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_words_letras_adivinadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='letras_adivinadas',
            field=models.CharField(default='', max_length=50),
        ),
    ]
