# Generated by Django 4.2.7 on 2023-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_words_letras_adivinadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='letras_adivinadas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='words',
            name='letras_incorrectas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
